### PR TITLE
feat: Consolidate api calls and handle errors

### PR DESCRIPTION
**Pull request by Ngkaokis**
ref #2586

require #4

### CODE REVIEW

**Comment by Ngkaokis** [comment]
Updated n8n webhook related endpoint.

Merge first. Feel free to leave comment.

**Comment by roxk** [comment]
@Ngkaokis Is the commit not pushed? Still seeing zapier-webhook mentioned @_@

**Comment by Ngkaokis** [comment]
Github issue....
image

**Comment by Ngkaokis** [comment]
Seems it's bugged....

Let me open another PR

**Comment by Ngkaokis** [comment]
Oh, I got it. It's my problem. 

As the repo is turned into public so the my fork somehow get disconnected :sosad:

**Pull request closed without merging**
